# Generated by Django 5.0.6 on 2024-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0008_remove_trabajador_usuario_remove_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
