# Generated by Django 5.0.7 on 2024-07-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado'), ('processing', 'En proceso')], default='pending', max_length=20),
        ),
    ]
