# Generated by Django 5.0.7 on 2024-07-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_paymentschedule_order_paymentschedule_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('schedule', 'installment_number')},
        ),
    ]
