# Generated by Django 5.0.7 on 2024-07-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_is_paid_paymentschedule_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='shop.order'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
