# Generated by Django 5.0.7 on 2024-07-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_outstanding_debt',
            field=models.BooleanField(default=False),
        ),
    ]
