# Generated by Django 5.0.6 on 2024-06-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0002_rename_name_proveedor_nombre_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('*', 'Eliminado')], default='A', max_length=1),
        ),
    ]
