# Generated by Django 5.0.6 on 2024-06-10 05:15

import appdeudas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0004_rename_name_producto_nombre_remove_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default=appdeudas.models.Pedido.generate_pedido_number, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=appdeudas.models.Producto.generate_codigo, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
