# Generated by Django 5.0.6 on 2024-06-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0010_pedido_estaado_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estaado_deuda',
            new_name='estado_deuda',
        ),
    ]
