# Generated by Django 5.0.6 on 2024-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('*', 'Eliminado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
