# Generated by Django 5.0.6 on 2024-06-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0003_proveedor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='TEMPVAL', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=6)),
                ('cliente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_pedido', models.CharField(choices=[('C', 'Contado'), ('D', 'A crédito')], max_length=1)),
                ('metodo_pago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta'), ('B', 'Billetera Virtual')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('*', 'Eliminado')], default='A', max_length=1)),
                ('productos', models.ManyToManyField(to='appdeudas.producto')),
            ],
        ),
    ]
