# Generated by Django 5.0.6 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0007_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
