# Generated by Django 5.0.6 on 2024-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0011_rename_estaado_deuda_pedido_estado_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_deuda',
            field=models.CharField(choices=[('V', 'Vigente'), ('C', 'Cerrado')], max_length=1),
        ),
    ]
