# Generated by Django 5.0.6 on 2024-06-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeudas', '0012_alter_pedido_estado_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado_deuda',
            new_name='estado_pedido',
        ),
    ]
