# Generated by Django 5.0.7 on 2024-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
