# Generated by Django 5.0.6 on 2024-07-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_paymentschedule_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('*', 'Deleted')], max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='record_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.recordstatus'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='record_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.recordstatus'),
        ),
    ]
