# Generated by Django 5.0.6 on 2024-07-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_recordstatus_product_record_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordstatus',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
